[package]
name = "dto_derive"
version = "0.1.0"
authors = ["Michał Blinkiewicz <michal.blinkiewicz@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.25", features = ["extra-traits"] }
quote = "0.6.10"
